using MG64Lib.Attributes;

namespace MG64Lib.GameData
{
    public enum SoundEffect
    {
        [Name("Rain"), InternalName("AE01")]
        Rain,
        [Name("Water"), InternalName("AE05")]
        Water,

        [Name("Grass hit 1"), InternalName("BL01")]
        GrassHit1,
        [Name("Grass hit 2"), InternalName("BL02")]
        GrassHit2,
        [Name("Mud hit"), InternalName("BL03")]
        MudHit,
        [Name("Sand hit"), InternalName("BL04")]
        SandHit,
        [Name("Wood hit"), InternalName("BL05")]
        WoodHit,
        [Name("Thunder 1"), InternalName("BL06")]
        Thunder1,
        [Name("Water hit 1"), InternalName("BL07")]
        WaterHit1,
        [Name("Water hit 2"), InternalName("BL08")]
        WaterHit2,
        [Name("Tree hit"), InternalName("BL09")]
        TreeHit,
        [Name("Bush hit"), InternalName("BL10")]
        BushHit,
        [Name("Boing"), InternalName("BL11")]
        Boing,
        [Name("Fall"), InternalName("BL14")]
        Fall,
        [Name("Pin hit"), InternalName("BL15")]
        PinHit,
        [Name("Flag hit 1"), InternalName("BL16")]
        FlagHit1,
        [Name("Cup hit 1"), InternalName("BL17")]
        CupHit1,
        [Name("Cup hit 2"), InternalName("BL18")]
        CupHit2,
        [Name("Cup hit 3"), InternalName("BL19")]
        CupHit3,
        [Name("Gust"), InternalName("BL20")]
        Gust,
        [Name("White noise"), InternalName("BL22")]
        WhiteNoise,
        [Name("Metal hit"), InternalName("BL23")]
        MetalHit,

        [Name("Birds - bull-headed shrike"), InternalName("BR01MOZU")]
        Birds1,
        [Name("Birds - cuckoo"), InternalName("BR02KAKKO")]
        Birds2,
        [Name("Birds - canary"), InternalName("BR03KANARIA")]
        Birds3,
        [Name("Birds - Japanese white-eye"), InternalName("BR04MEJIRO")]
        Birds4,
        [Name("Birds - sparrow 1"), InternalName("BR05SUZUME")]
        Birds5,
        [Name("Birds - sparrow 2"), InternalName("BR06SUZUME2")]
        Birds6,
        [Name("Birds - lark 1"), InternalName("BR07HIBARI")]
        Birds7,
        [Name("Birds - lark 2"), InternalName("BR08HIBARI1")]
        Birds8,
        [Name("Birds - kingfisher"), InternalName("BR09KAWASEMI")]
        Birds9,
        
        FlagHit2,
        MenuSfx1,
        MenuSfx2,
        MenuSfx3,
        SpeedGolfCountdown1,
        SpeedGolfCountdown2,
        MenuSfx4,
        ImpactTargeting,
        MenuSfx5,
        MenuSfx6,
        KoopaTroopa,
        MenuSfx7,
        ChainChomp,
        Monkey,
        Thwomp,
        Fireball1,
        Star1,
        Fireball2,
        Fireworks1,
        Fireworks2,
        Coin,
        MenuSfx8,
        Skid,
        MenuSfx9,
        MenuSfx10,
        OrchestraHit,
        BlockHit,
        Bang1,
        MenuSfx11,
        Star2,
        Dizzy,
        Swipe,
        Clap1,
        Clap2,
        Bang2,
        Bang3,
        Star3,
        Star4,
        Camera,
        MenuSfx12,
        MenuSfx13,
        MenuSfx14,
        MenuSfx15,
        MenuSfx16,
        MenuSfx17,
        MenuSfx18,
        MenuSfx19,
        MenuSfx20,
        MenuSfx21,
        ClubHit1,
        ClubHit2,
        ClubHit3,
        ClubHit4,
        ClubHit5,
        ClubHit6,
        ClubHit7,
        ClubHit8,
        WaterHit3,
        BallFlight1,
        BallFlight2,
        ClubSwitch,
        MenuSfx22,
        MenuSfx23,
        MenuSfx24,
        MenuSfx25,
        MenuSfx26,
        MenuSfx27,
        MenuSfx28,
        MenuSfx29,
        MenuSfx30,
        MenuSfx31,
        MenuSfx32,
        MenuSfx33,
        MenuSfx34,
        MenuSfx35,
        MenuSfx36,
        MenuSfx37,
        MenuSfx38,
        MenuSfx39,
        MenuSfx40,
        MenuSfx41,
        MenuSfx42,
        Thunder2,
        ToadAhh,
        ToadOkay1,
        Applause1,
        Applause2,
        Applause3,
        ToadOB,
        ToadYeah,
        ToadTryAgain,
        ToadOkay2,
        NarratorNiceShot,
        NarratorOhTooBad,
        NarratorWonderful,
        NarratorExcellent,
        NarratorGreat,
        NarratorNiceOn,
        NarratorNiceApproach,
        NarratorNiceTouch,
        NarratorFore,
        NarratorWowHoleInOne,
        NarratorOohNiceAlbatross,
        NarratorNiceEagle,
        NarratorNiceBirdie,
        NarratorNicePar,
        NarratorNiceIn,
        NarratorHurryUpPlease,
        NarratorGood,
        NarratorOkay,
        NarratorCongratulations,
        NarratorTryThatAgain,
        NarratorReadyGo,
        NarratorFinish,
        NarratorFlagShot,
        NarratorChipIn,
        NarratorPinShot,
        NarratorNice,
        NarratorAlright,
        NarratorHoleComplete,
        NarratorDuffedIt,
        NarratorBogey,
        NarratorOohIntoTheRough,
        NarratorToughLie,
        NarratorFantasticPutt,
        NarratorGreatRoundOfGolf,
        NarratorVeryWellPlayed,

        AzaleaHahaha,
        MarioWeeHee1,
        AzaleaHereIAm,
        AzaleaAlright,
        AzaleaOh,
        MarioWeeHee2,
        AzaleaOhNo,
        AzaleaFine,
        AzaleaHereWeGo,
        AzaleaYahooHahaha,
        AzaleaYeah,
        AzaleaGoodShot,
        AzaleaNiceShot,
        AzaleaWonderful,
        AzaleaExcellent,
        AzaleaBeautiful,
        AzaleaOkay,
        AzaleaHurryUp,
        AzaleaFore,
        AzaleaSigh,
        AzaleaWooHoo,

        BabyMarioHahaha,
        BabyMarioWow,
        BabyMarioHello,
        BabyMarioAlright,
        BabyMarioOh,
        BabyMarioMammaMia,
        BabyMarioOhNo,
        MarioWeeHee3,
        BabyMarioHereWeGo,
        BabyMarioYahoo,
        BabyMarioYeah,
        BabyMarioGoodShot,
        BabyMarioNiceShot1,
        BabyMarioWonderful,
        BabyMarioExcellent,
        BabyMarioBeautiful,
        BabyMarioOkay,
        BabyMarioHurryUp,
        BabyMarioFore,
        BabyMarioWooHoo,
        BabyMarioNumberOne,
        BabyMarioNiceShot2,
        BabyMarioHm,
        BabyMarioWee,
        BabyMarioWahWahWah,

        CharlieHahaha,
        CharlieWow,
        CharlieHereIAm,
        CharlieAlright,
        MarioWeeHee4,
        MarioWeeHee5,
        CharlieOhNo,
        CharlieFine,
        CharlieHereWeGo,
        CharlieYeehah,
        CharlieYeah,
        CharlieGoodShot,
        CharlieNiceShot,
        CharlieWonderful,
        CharlieExcellent,
        CharlieBeautiful,
        CharlieOkay,
        CharlieHurryUp,
        CharlieIsTops,
        CharlieFore,
        CharlieOh,
        CharlieWhoTheMan,

        DK1,
        DK2,
        DK3,
        DK4,
        DK5,
        DK6,
        DK7,
        DK8,
        DK9,
        DK10,
        DK11,
        DK12,
        DK13,

        HarryHahaha,
        HarryWow,
        HarryHereIAm,
        HarryAlright,
        MarioWeeHee6,
        MarioWeeHee7,
        HarryOhNo,
        HarryFine,
        HarryHereWeGo,
        HarryYahoo,
        HarryYeah,
        HarryGoodShot,
        HarryNiceShot,
        HarryWonderful,
        HarryExcellent,
        HarryBeautiful,
        HarryOkay,
        HarryHurryUp,
        HarryIsTops,
        HarryFore,
        HarryOh,
        HarryWoo,
        HarryYes,

        JoeHahaha,
        MarioWeeHee8,
        JoeHereIAm,
        JoeAlright,
        MarioWeeHee9,
        MarioWeeHee10,
        JoeOhNo,
        JoeFine,
        JoeHereWeGo,
        JoeYahoo1,
        JoeYeah,
        JoeGoodShot,
        JoeNiceShot,
        JoeWonderful,
        JoeExcellent,
        JoeBeautiful,
        JoeOkay,
        JoeHurryUp,
        JoeFore,
        JoeOh,
        JoeWoo,
        JoeYahoo2,

        KidHahaha,
        KidHereIAm,
        KidAlright,
        KidOh1,
        KidOhNo,
        KidFine,
        KidHereWeGo,
        KidYahoo1,
        KidYeah,
        KidGoodShot,
        KidNiceShot,
        KidWonderful,
        KidExcellent,
        KidBeautiful,
        KidOkay,
        KidHurryUp,
        KidFore,
        KidOh2,
        KidYes,

        Bowser1,
        Bowser2,
        Bowser3,
        Bowser4,
        Bowser5,
        Bowser6,
        Bowser7,
        Bowser8,
        Bowser9,
        Bowser10,
        Bowser11,
        Bowser12,
        Bowser13,

        LuigiHahaha,
        LuigiWow,
        LuigiHereIAm,
        LuigiAlright,
        LuigiMammaMia,
        LuigiOhNo,
        LuigiFine,
        LuigiHereWeGo,
        LuigiYahoo,
        LuigiYeah,
        LuigiGoodShot,
        LuigiNiceShot,
        LuigiWonderful,
        LuigiExcellent,
        LuigiOkay,
        LuigiHurryUp,
        LuigiIsTops,
        LuigiFore,
        LuigiHm,
        LuigiIsNumberOne,
        LuigiPrettyGood,
        LuigiOh1,
        LuigiOh2,

        MapleHahaha,
        MarioWeeHee11,
        MapleHereIAm,
        MapleAlright,
        MapleOh1,
        MarioWeeHee12,
        MapleOhNo,
        MapleFine,
        MapleHereWeGo,
        MapleYahoo,
        MapleYeah,
        MapleGoodShot,
        MapleNiceShot,
        MapleWonderful,
        MapleExcellent,
        MapleBeautiful,
        MapleOkay,
        MapleHurryUp,
        MapleIsTops,
        MapleFore,
        MapleOh2,
        MapleWooHoo,
        MapleOhYes,

        MarioHahaha1,
        MarioWeeHee13,
        MarioHereIAm,
        MarioAlright,
        MarioOh1,
        MarioMammaMia,
        MarioOhNo,
        MarioFine,
        MarioHereWeGo,
        MarioYahoo,
        MarioYeah,
        MarioMarioGolf,
        MarioGoodShot,
        MarioNiceShot,
        MarioWonderful,
        MarioExcellent,
        MarioBeautiful,
        MarioOkay,
        MarioHurryUp,
        MarioIsTops,
        MarioFore,
        MarioHm,
        MarioWooHooHoo,
        MarioTheBest,
        MarioWhistle,
        MarioAhh,
        MarioHahaha2,
        MarioHahaha3,
        MarioMario,
        MarioItsaMe,
        MarioHelloBall,
        MarioUhOh,
        MarioOh2,

        PeachHahaha,
        PeachOh1,
        PeachHereIAm,
        PeachAlright,
        PeachOh2,
        PeachMammaMia,
        PeachOhNo,
        PeachFine,
        PeachHereWeGo,
        PeachYahoo,
        PeachYeah,
        PeachGoodShot,
        PeachNiceShot,
        PeachWonderful,
        PeachExcellent,
        PeachBeautiful,
        PeachOkay,
        PeachHurryUp,
        PeachIsTops,
        PeachFore,
        PeachHm,
        PeachWinsAgain,
        PeachHeyMario1,
        PeachHeyMario2,

        PlumHahaha1,
        PlumWow,
        PlumHereIAm,
        PlumAlright,
        PlumOh1,
        MarioWeeHee14,
        PlumOhNo,
        PlumFine,
        PlumHereWeGo,
        PlumYipee,
        PlumYay,
        PlumGoodShot,
        PlumNiceShot,
        PlumWonderful,
        PlumExcellent,
        PlumBeautiful,
        PlumOkay,
        PlumHurryUp,
        PlumIsTops,
        PlumFore,
        PlumOh2,
        PlumLookingGood,
        PlumYes,
        PlumHahaha2,

        SonnyHahaha1,
        SonnyWow,
        SonnyHereIAm,
        SonnyAlright,
        MarioWeeHee15,
        MarioWeeHee16,
        SonnyOhNo,
        SonnyFine,
        SonnyLetsPlay,
        SonnyYahoo,
        SonnyYeehah,
        SonnyGoodShot,
        SonnyNiceShot1,
        SonnyWonderful,
        SonnyExcellent,
        SonnyBeautiful,
        SonnyOkay,
        SonnyHurryUp,
        SonnyIsTops,
        SonnyFore,
        SonnyOh,
        SonnySonnyDay,
        SonnyYes,
        SonnyHereWeGo,
        SonnyNiceShot2,

        SherryHahaha,
        SherryWow,
        SherryHereIAm,
        SherryAlright,
        MarioWeeHee17,
        MarioWeeHee18,
        SherryOhNo,
        SherryFine,
        SherryHereWeGo,
        SherryYahoo1,
        SherryYeah,
        SherryGoodShot,
        SherryNiceShot,
        SherryWonderful,
        SherryExcellent,
        SherryBeautiful,
        SherryOkay,
        SherryHurryUp,
        SherryYay,
        SherryFore,
        SherryOh,
        SherryThumbsUp,

        WarioHahaha,
        WarioWow,
        WarioHereIAm,
        WarioAlright,
        WarioMammaMia,
        WarioUhOh,
        WarioFine,
        WarioHereWeGo,
        WarioYahoo,
        WarioYeah,
        WarioWarioGolf64,
        WarioGoodShot,
        WarioNiceShot,
        WarioWonderful,
        WarioExcellent,
        WarioBeautiful,
        WarioOkay,
        WarioHurryUp,
        WarioIsTops,
        WarioFore,
        WarioIsTheBest,
        WarioSuperDuper,

        [Name("Yoshi - 1"), InternalName("CYS00")]
        Yoshi1,
        [Name("Yoshi - 2"), InternalName("CYS01")]
        Yoshi2,
        [Name("Yoshi - 3"), InternalName("CYS02")]
        Yoshi3,
        [Name("Yoshi - 4"), InternalName("CYS03")]
        Yoshi4,
        [Name("Yoshi - 5"), InternalName("CYS04")]
        Yoshi5,
        [Name("Yoshi - 6"), InternalName("CYS05")]
        Yoshi6,
        [Name("Yoshi - 7"), InternalName("CYS06")]
        Yoshi7,
        [Name("Yoshi - 8"), InternalName("CYS07")]
        Yoshi8,
        [Name("Yoshi - 9"), InternalName("CYS08")]
        Yoshi9,
        [Name("Yoshi - 10"), InternalName("CYS13")]
        Yoshi10,
        [Name("Yoshi - 11"), InternalName("CYS14")]
        Yoshi11,
        [Name("Yoshi - 12"), InternalName("CYS17")]
        Yoshi12,
        [Name("Yoshi - 13"), InternalName("CYS18")]
        Yoshi13,
        [Name("Yoshi - 14"), InternalName("CYS19")]
        Yoshi14,
        [Name("Yoshi - 15"), InternalName("CYS20")]
        Yoshi15,
        [Name("Yoshi - 16"), InternalName("CYS21")]
        Yoshi16,

        [Name("Mario Golf 64"), InternalName("TITLE")]
        MarioGolf64,
        [Name("Welcome to Mario Golf 1"), InternalName("USATITLE")]
        WelcomeToMarioGolf1,
        [Name("Welcome to Mario Golf 2"), InternalName("USATITLE01")]
        WelcomeToMarioGolf2,
        [Name("Welcome to Mario Golf 3"), InternalName("USATITLE02")]
        WelcomeToMarioGolf3,
        [Name("Mario - hahaha 4"), InternalName("WARAI3")]
        MarioHahaha4
    }
}